name: wildmanager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+20260317

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_map: ^6.1.0
  http: ^1.2.0
  latlong2: ^0.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  wildlifenl_login_components:
    git:
      url: https://github.com/WildLife-NL/wildlifenl-components.git
      ref: main
      path: wildlifenl_login_components
  wildlifenl_map_logic_components:
    git:
      url: https://github.com/WildLife-NL/wildlifenl-components.git
      ref: main
      path: wildlifenl_map_logic_components
  wildlifenl_map_ui_components:
    git:
      url: https://github.com/WildLife-NL/wildlifenl-components.git
      ref: main
      path: wildlifenl_map_ui_components
  wildlifenl_interaction_components:
    git:
      url: https://github.com/WildLife-NL/wildlifenl-components.git
      ref: main
      path: wildlifenl_interaction_components
  wildlifenl_detection_components:
    git:
      url: https://github.com/WildLife-NL/wildlifenl-components.git
      ref: main
      path: wildlifenl_detection_components
  wildlifenl_visitation_components:
    git:
      url: https://github.com/WildLife-NL/wildlifenl-components.git
      ref: main
      path: wildlifenl_visitation_components
  wildlifenl_assets:
    git:
      url: https://github.com/WildLife-NL/wildlifenl-components.git
      ref: main
      path: wildlifenl_assets_components
  wildlifenl_animal_components:
    git:
      url: https://github.com/WildLife-NL/wildlifenl-components.git
      ref: main
      path: wildlifenl_animal_components

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - assets/icons/animals/bever.png
    - assets/icons/animals/boommarter.png
    - assets/icons/animals/bunzing.png
    - assets/icons/animals/damhert.png
    - assets/icons/animals/das.png
    - assets/icons/animals/edelhert.png
    - assets/icons/animals/eekhoorn.png
    - assets/icons/animals/egel.png
    - assets/icons/animals/europese_nerts.png
    - assets/icons/animals/exmoorpony.png
    - assets/icons/animals/galloway.png
    - assets/icons/animals/goudjakhals.png
    - assets/icons/animals/haas.png
    - assets/icons/animals/hermelijn.png
    - assets/icons/animals/hooglander.png
    - assets/icons/animals/konijn.png
    - assets/icons/animals/konikpaard.png
    - assets/icons/animals/otter.png
    - assets/icons/animals/ree.png
    - assets/icons/animals/shetlandpony.png
    - assets/icons/animals/steenmarter.png
    - assets/icons/animals/taurus.png
    - assets/icons/animals/vos.png
    - assets/icons/animals/wezel.png
    - assets/icons/animals/wild_kat.png
    - assets/icons/animals/wild_zwijn.png
    - assets/icons/animals/wisent.png
    - assets/icons/animals/woelrat.png
    - assets/icons/animals/wolf.png
